### ISSUE TITLE
 Best Time to Buy and Sell Stock II

### ISSUE THREAD

**Issue by Azhar221** [Azhar221/DSA-Sheet#29]

**Comment by AdiTyaa-Raj** [comment]
Hey @Azhar221 , Pls assign this issue to me. I can code this in C++.

**Comment by Azhar221** [comment]
put your code inside of MOHAMMAD FRAZ DSA/

**Comment by AdiTyaa-Raj** [comment]
#45 kindly merge the pull request @Azhar221
