### ISSUE TITLE
 Subarray Sums I

### ISSUE THREAD

**Issue by Azhar221** [Azhar221/DSA-Sheet#40]

**Comment by utkarsh2709** [comment]
Hello @Azhar221, Pls assign this issue to me. I can code this in Java and C++.

**Comment by Azhar221** [comment]
put your code inside of MOHAMMAD FRAZ DSA/

**Comment by utkarsh2709** [comment]
Sure @Azhar221. Just wanted to confirm you want the Maximum subarray sum or  Sum of all the subarrays.
